image: node:10.15.3

stages:
  - build
  - test
  - package
  - deploy

cache:
  key: "default"
  paths:
    - node_modules/  

before_script:
  - npm run clean-install

build:
  stage: build
  tags:
    - docker
  script:
    - npm run compile

test:
  stage: test
  tags:
    - docker
  script:
    - npm run compile
    - cd proxy/
    - DEBUG=openapi-cop:* npm test

package:
  stage: package
  tags:
    - docker
  script:
    - npm pack
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - proxy/openapi-cop-proxy-*.tgz

# publish:  
#   stage: deploy
#   tags:
#     - docker
#   only:
#     - master
#     - tags
#     - triggers
#   script:
#     - npm run build
#     - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
#     - npm publish