name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (mock)
      working-directory: ./mock
      run: npm install
    - name: Build mock
      working-directory: ./mock
      run: npm run compile
    - name: Install dependencies (proxy)
      run: npm install
    - run: npm test
      env:
        DEBUG: openapi-cop:*
        CI: true
    - name: Test dependencies
      run: npm run test:deps
